version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /voice
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /packaging
    schedule:
      interval: weekly
    labels:
      - dependencies
